### PR TITLE
feat: allow updating settings for other repositories

### PR DESCRIPTION
**Pull request by alejandrohdezma**
First of all, thank you very much for developing this action. It is great!

# What has been done in this PR?

- Add new `github-repository` input that can be used to indicate the repository to update.
- The previous value is not required so the action will fallback to `GITHUB_REPOSITORY` environment variable so it is backward compatible.

### CODE REVIEW

**Comment by mattsb42** [comment]
Thanks for the contribution. :)

I was initially conflicted on the idea of managing one repo from an action in another, but the more I think about it, the more I like the idea. Maybe not for all settings, but it would definitely make things like managing standardized settings across many repos a lot easier.

It looks like this is currently blocked on some updates that the new pylint update is requiring (note to self: do #53 to catch things like this before a PR next time.) I'll clean that up and then we can update this branch with those changes.

Aside from that, I would like to see some tests to make sure that `load_context()` is doing the expected thing for:

- [ ] `GITHUB_REPOSITORY` set, `INPUT_GITHUB-REPOSITORY` not set
- [ ] `GITHUB_REPOSITORY` not set, `INPUT_GITHUB-REPOSITORY` set
- [ ] `GITHUB_REPOSITORY` set, `INPUT_GITHUB-REPOSITORY` set

That should be doable by extending and parametrizing the existing test for `load_context()`.

https://github.com/mattsb42/repo-manager/blob/0bef9d6f85e67c54201f89a9a1668dafa8e3d73f/test/unit/test_util.py#L54-L60

**Comment by alejandrohdezma** [comment]
> I was initially conflicted on the idea of managing one repo from an action in another, but the more I think about it, the more I like the idea. Maybe not for all settings, but it would definitely make things like managing standardized settings across many repos a lot easier.

Yeah, that's exactly how I'm using it :)

> It looks like this is currently blocked on some updates that the new pylint update is requiring (note to self: do #53 to catch things like this before a PR next time.) I'll clean that up and then we can update this branch with those changes.

Great! Thanks!

> Aside from that, I would like to see some tests to make sure that `load_context()` is doing the expected thing for:
> 
>     * [ ]  `GITHUB_REPOSITORY` set, `INPUT_GITHUB-REPOSITORY` not set
> 
>     * [ ]  `GITHUB_REPOSITORY` not set, `INPUT_GITHUB-REPOSITORY` set
> 
>     * [ ]  `GITHUB_REPOSITORY` set, `INPUT_GITHUB-REPOSITORY` set

I'm not a Python developer but I'll try to do my best and create a new commit with the tests :)

Thank you!!

**Review by mattsb42 — APPROVED** [review]
Since I finally got the other issues sorted out, I'm going to go ahead and merge this and add in the tests. Shooting for a release today. :)

**Comment by alejandrohdezma** [comment]
Thank you very much!

**Pull request merged**
